#!/bin/env bash

XXX=$PS1

# get branch
function gitty()
{
    declare status
    declare star

    # two layers deep -- Ben Carson
    for path in {'.','..','../..'}/.git/HEAD
    do
        if [[ -r $path ]]
        then
            branch=$(<"${path}")
            branch="${branch//*\//}"

            # if ! git diff --quiet
            # then
            #     star=$'*'
            # fi
            status+="« ${star}${branch} »"

            # dirbase=$(dirname "${path}")

            # hash=$(<"${dirbase}/refs/heads/${branch}")

            break
        fi
    done

    export PS1="${status}${XXX}"
}
export PROMPT_COMMAND=gitty
