#!/bin/env bash

XXX=$PS1

# get branch
function gitty()
{
    declare status

    if [[ -r .git/HEAD ]]
    then
        branch=$(<.git/HEAD)
        branch="${branch//*\//}"
        status+="« ${branch} »"
    fi

    export PS1="${status}${XXX}"
}
export PROMPT_COMMAND=gitty
