#!/bin/env bash

[[ $PROMPT_COMMAND = "sparseline_ps1" ]] && return
unset _PS1
_PS1=$PS1

function sparseline_ps1()
{

    local __return_code=$?
    # preserve shopt settings
    prvOpt=$(shopt -p extglob nullglob|sed ':a;N;$!ba;s/\n/;/g')
    shopt -s extglob;
    shopt -s nullglob;
    :
    local sparseline_status
    :
    local path
    local dirbase
    local re
    local S
    local R
    local B
    local H
    local T
    local X
    local C; # commit difference
    :
    local D
    if [[ ${LC_ALL:-${LC_CTYPE:-$LANG}} == *UTF-8 ]]; then
        D=$'\uE0B0'
        S=$'\u25CF'
        :
        local _b_="\\[\\033[48;5;"
        local _f_="\\[\\033[38;5;"
        local __="\\[\\033[m\\]"


        local r_="${_f_}219m\\]"
        local _r="${_b_}219m\\]"

        local b_="${_f_}33m\\]"
        local _b="${_b_}33m\\]"

        local g_="${_f_}40m\\]"
        local _g="${_b_}40m\\]"

        local k_="${_f_}232m\\]"
        local _k="${_b_}232m\\]"

        local w_="${_f_}231m\\]"

    else
        D='|'
        S='•'
    fi
    :

    for path in {'.','..','../..'}/.git/HEAD
    do
        [[ ! -r "${path}" ]] && continue
        S="${g_}${S}"
        [[ $__return_code -ne 0 ]] && S="${r_}×";

        dirbase=$(dirname "${path}")

        B=$(<"${path}")
        B="${B//*\//}"

        while read -r words
        do
            re=$"\\[remote \"(.*)\"\\]"
            [[ "${words}" =~ ${re} ]] && R="${BASH_REMATCH[1]}" && break
        done < "${dirbase:?}/config"

        R="${R:-remote?}" # give default value if otherwise undefined

        if [[ -r "${dirbase}/refs/heads/${B}" ]]
        then
            H=$(<"${dirbase}/refs/heads/${B}")
            H="${H:0:7}"
        else
            H=$''
            B="${B:0:7}#-------"
        fi
        for tag_path in ${dirbase}/refs/tags/*
        do
            X=$(<"${tag_path}")
            [[ $H == "${X:0:7}" ]] && \
                T=$(basename "${tag_path}") && \
                H="${T}"
        done
        sparseline_status="${_k} ${S} ${_b}${w_}${R:+$R/}${B}${H:+#$H}${C}${__}${b_}${D}${__}"
        :
    done
    export PS1="${sparseline_status}${_PS1}"
    # restore shopt settings
    eval "${prvOpt}"
    return 0
}
PROMPT_COMMAND="sparseline_ps1"
